baseURL = "http://example.org/"
languageCode = "ja-jp"
theme = "hyde"
title = "rkgknet"
[params]
description = "ネット出張落書き帳"
disqusShortname = ""
googleAnalytics = ""
layoutReverse = true
themecolor = ""

