baseURL = "http://blog.rkgknet.org/"
languageCode = "ja-JP"
title = "rkgknet"
theme = "mainroad"
disqusShortname = "rkgknet"
googleAnalytics = "G-CRMT97QGNY"
hasCJKLanguage = true
summaryLength = 160
[markup.goldmark.renderer]
  unsafe = true
[Params]
  copyright = "liqsuq"
  readmore = true
  post_meta = ["date", "categories"]
  googleFontsLink = "https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700;900&display=swap"
  customCSS = ["css/custom.css"]
[Params.style.vars]
  highlightColor = "#999999"
  fontFamilyPrimary = "'Open Sans', 'Noto Sans JP', Helvetica, Arial, sans-serif"
[Params.logo]
  title = "rkgknet"
  subtitle = "ネット出張落書き帳"
[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["recent", "categories", "taglist", "social"]
[Params.widgets]
  tags_counter = true
[[Menus.main]]
  name = "Home"
  url = "/"
  weight = 1
